name: CI - Test and Build for Development

on:
  push:
    branches: [ develop ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - '.github/workflows/ci.dev.yml'
  pull_request:
    branches: [ develop ]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile

      - name: Run frontend tests
        run: |
          cd frontend
          yarn test -- --run

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'yarn'
          cache-dependency-path: 'backend/yarn.lock'

      - name: Install backend dependencies
        run: |
          cd backend
          yarn install --frozen-lockfile

      - name: Run backend tests
        run: |
          cd backend
          yarn test -- --run