name: Frontend CI - Test and Build

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'yarn'
          cache-dependency-path: 'frontend/yarn.lock'

      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile

      - name: Run frontend tests
        run: |
          cd frontend
          yarn test -- --run

      - name: Build frontend project
        run: |
          cd frontend
          yarn build